import { create } from 'zustand';

export type Language = 'vi' | 'en';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
}

export const useLanguageStore = create<LanguageState>()((set) => ({
  language: 'vi',
  setLanguage: (lang) => set({ language: lang }),
  toggleLanguage: () => set((state) => ({
    language: state.language === 'vi' ? 'en' : 'vi'
  })),
}));

// ============ Translations ============

export const translations = {
  vi: {
    // Common
    settings: 'Cài đặt',
    back: 'Quay lại',
    profile: 'Hồ sơ',
    logout: 'Đăng xuất',
    save: 'Lưu',
    cancel: 'Hủy',
    edit: 'Sửa',
    delete: 'Xóa',
    create: 'Tạo',
    search: 'Tìm kiếm',
    close: 'Đóng',
    done: 'Xong',
    confirm: 'Xác nhận',
    success: 'Thành công',
    error: 'Lỗi',
    loading: 'Đang tải...',
    noData: 'Không có dữ liệu',
    refresh: 'Làm mới',
    all: 'Tất cả',
    active: 'Hoạt động',
    inactive: 'Không hoạt động',
    pending: 'Chờ duyệt',
    rejected: 'Từ chối',
    suspended: 'Tạm ngưng',
    retry: 'Thử lại',
    submit: 'Gửi',
    yes: 'Có',
    no: 'Không',

    // Navigation
    chat: 'Trò chuyện AI',
    history: 'Lịch sử',
    documents: 'Tài liệu',
    analytics: 'Phân tích',
    profile: 'Hồ sơ',
    newChat: 'Tạo cuộc trò chuyện mới',
    manageEmployees: 'Quản lý nhân viên',
    approveTenant: 'Duyệt tổ chức',
    subscription: 'ĐĂNG KÝ GÓI',
    aiSettings: 'Cài đặt AI',
    organizationSettings: 'Cài đặt tổ chức',

    // App
    appTitle: 'AI Chatbot',
    appSubtitle: 'Dành cho Tenant',

    // Auth
    login: 'Đăng nhập',
    logout: 'Đăng xuất',
    email: 'Email',
    password: 'Mật khẩu',
    forgotPassword: 'Quên mật khẩu?',
    loginButton: 'Đăng nhập',
    loginError: 'Không thể đăng nhập. Vui lòng thử lại.',
    sessionExpired: 'Phiên đăng nhập hết hạn. Vui lòng đăng nhập lại.',
    welcomeBack: 'Chào mừng trở lại!',
    signInContinue: 'Đăng nhập để tiếp tục',
    enterEmail: 'Nhập email của bạn',
    enterPassword: 'Nhập mật khẩu',

    // Analytics
    useAI: 'Sử dụng AI',
    totalRequests: 'Tổng số yêu cầu',
    tokensUsed: 'Số Token đã dùng',
    today: 'Hôm nay',
    thisMonth: 'Tháng này',
    requests: 'Yêu cầu',
    documents: 'Tài liệu',
    totalDocuments: 'Tổng số tài liệu',
    totalChunks: 'Tổng số đoạn',
    avgChunks: 'TB đoạn/tài liệu',
    avgPerRequest: 'TB/request',
    embeddingStatus: 'Tình trạng xử lý tài liệu',
    embeddingDetails: 'Chi tiết xử lý',
    completed: 'Hoàn tất',
    processing: 'Đang xử lý',
    waiting: 'Đang chờ',
    failed: 'Thất bại',
    overview: 'Tổng quan',
    aiActivity: 'Hoạt động AI',
    updated: 'Cập nhật',
    pullToRefresh: 'Kéo để làm mới',

    // Employee Management
    manageEmployees: 'Quản lý nhân viên',
    manageTenants: 'Quản lý tổ chức',
    approveTenant: 'Duyệt tổ chức',
    employeeList: 'Danh sách nhân viên',
    total: 'Tổng',
    activate: 'Kích hoạt',
    deactivate: 'Vô hiệu hóa',
    resetPassword: 'Đặt lại mật khẩu',
    viewDetails: 'Xem chi tiết',
    fullName: 'Họ và tên',
    phone: 'Điện thoại',
    role: 'Vai trò',
    department: 'Phòng ban',
    createdAt: 'Ngày tạo',
    lastLogin: 'Đăng nhập cuối',
    noEmployees: 'Không có nhân viên nào',

    // Chat
    chatPlaceholder: 'Nhập tin nhắn của bạn...',
    send: 'Gửi',
    thinking: 'Đang suy nghĩ...',
    noHistory: 'Chưa có cuộc trò chuyện nào',
    startConversation: 'Bắt đầu trò chuyện với AI',
    askAnything: 'Hỏi tôi bất cứ điều gì về chính sách công ty, HR, IT...',
    sources: 'Nguồn tài liệu',
    helpful: 'Hữu ích',
    notHelpful: 'Không hữu ích',
    thanks: 'Cảm ơn!',
    feedbackReceived: 'Đã ghi nhận',
    responseTime: 'Phản hồi trong',
    ms: 'ms',
    rateResponse: 'Đánh giá câu trả lời',

    // Profile
    editProfile: 'Chỉnh sửa hồ sơ',
    updateSuccess: 'Cập nhật thành công',
    updateError: 'Không thể cập nhật. Vui lòng thử lại.',
    personalInfo: 'Thông tin cá nhân',
    contact: 'Liên hệ',
    security: 'Bảo mật',
    changePassword: 'Đổi mật khẩu',
    currentPassword: 'Mật khẩu hiện tại',
    newPassword: 'Mật khẩu mới',
    confirmPassword: 'Xác nhận mật khẩu',
    passwordChanged: 'Mật khẩu đã được thay đổi',
    passwordMismatch: 'Mật khẩu mới không khớp',
    passwordTooShort: 'Mật khẩu phải có ít nhất 6 ký tự',
    contactEmail: 'Email liên hệ',
    updateEmail: 'Cập nhật email',
    sendOtp: 'Gửi mã OTP',
    enterOtp: 'Nhập mã OTP',
    verify: 'Xác minh',
    phoneNumber: 'Số điện thoại',
    dateOfBirth: 'Ngày sinh',
    address: 'Địa chỉ',
    notUpdated: 'Chưa cập nhật',

    // Settings
    settings: 'Cài đặt',
    language: 'Ngôn ngữ',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    theme: 'Giao diện',
    lightMode: 'Sáng',
    darkMode: 'Tối',

    // Role
    admin: 'Quản trị viên',
    staff: 'Nhân viên',
    employee: 'Nhân viên',
    user: 'Người dùng',
    tenant: 'Tenant',

    // Document
    uploadDocument: 'Tải lên tài liệu',
    documentTitle: 'Tiêu đề tài liệu',
    selectFile: 'Chọn file',
    upload: 'Tải lên',
    uploadSuccess: 'Tài liệu đã được tải lên thành công!',
    uploadError: 'Không thể tải lên tài liệu',
    internalDocuments: 'Tài liệu nội bộ công ty',
    noDocuments: 'Chưa có tài liệu nào',
    addDocuments: 'Thêm tài liệu để bắt đầu',
    processed: 'Đã xử lý',
    pending: 'Đang xử lý',
    uploadedAt: 'Tải lên lúc',
    fileSize: 'Dung lượng',
    new: 'MỚI',

    // Error
    cannotLoadData: 'Không thể tải dữ liệu.',
    noPermission: 'Bạn không có quyền xem nội dung này.',
    somethingWentWrong: 'Đã xảy ra lỗi',
    tryAgain: 'Thử lại',
  },

  en: {
    // Common
    settings: 'Settings',
    back: 'Back',
    profile: 'Profile',
    logout: 'Logout',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    create: 'Create',
    search: 'Search',
    close: 'Close',
    done: 'Done',
    confirm: 'Confirm',
    success: 'Success',
    error: 'Error',
    loading: 'Loading...',
    noData: 'No data',
    refresh: 'Refresh',
    all: 'All',
    active: 'Active',
    inactive: 'Inactive',
    pending: 'Pending',
    rejected: 'Rejected',
    suspended: 'Suspended',
    retry: 'Retry',
    submit: 'Submit',
    yes: 'Yes',
    no: 'No',

    // Navigation
    chat: 'AI Chat',
    history: 'History',
    documents: 'Documents',
    analytics: 'Analytics',
    profile: 'Profile',
    newChat: 'New Chat',
    aiSettings: 'AI Settings',
    organizationSettings: 'Organization Settings',

    // App
    appTitle: 'AI Chatbot',
    appSubtitle: 'For Tenants',

    // Auth
    login: 'Login',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    loginButton: 'Login',
    loginError: 'Cannot login. Please try again.',
    sessionExpired: 'Session expired. Please login again.',
    welcomeBack: 'Welcome back!',
    signInContinue: 'Sign in to continue',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',

    // Analytics
    useAI: 'AI Usage',
    totalRequests: 'Total Requests',
    tokensUsed: 'Tokens Used',
    today: 'Today',
    thisMonth: 'This Month',
    requests: 'Requests',
    documents: 'Documents',
    totalDocuments: 'Total Documents',
    totalChunks: 'Total Chunks',
    avgChunks: 'Avg chunks/doc',
    avgPerRequest: 'Avg/request',
    embeddingStatus: 'Embedding Status',
    embeddingDetails: 'Embedding Details',
    completed: 'Completed',
    processing: 'Processing',
    waiting: 'Waiting',
    failed: 'Failed',
    overview: 'Overview',
    aiActivity: 'AI Activity',
    updated: 'Updated',
    pullToRefresh: 'Pull to refresh',

    // Employee Management
    manageEmployees: 'Manage Employees',
    manageTenants: 'Manage Tenants',
    approveTenant: 'Approve Tenant',
    employeeList: 'Employee List',
    total: 'Total',
    activate: 'Activate',
    deactivate: 'Deactivate',
    resetPassword: 'Reset Password',
    viewDetails: 'View Details',
    fullName: 'Full Name',
    phone: 'Phone',
    role: 'Role',
    department: 'Department',
    createdAt: 'Created At',
    lastLogin: 'Last Login',
    noEmployees: 'No employees found',

    // Subscription
    subscription: 'SUBSCRIPTION',

    // Chat
    chatPlaceholder: 'Enter your message...',
    send: 'Send',
    thinking: 'Thinking...',
    noHistory: 'No conversations yet',
    startConversation: 'Start a conversation with AI',
    askAnything: 'Ask me anything about company policies, HR, IT...',
    sources: 'Document Sources',
    helpful: 'Helpful',
    notHelpful: 'Not helpful',
    thanks: 'Thanks!',
    feedbackReceived: 'Feedback received',
    responseTime: 'Response in',
    ms: 'ms',
    rateResponse: 'Rate this response',

    // Profile
    editProfile: 'Edit Profile',
    updateSuccess: 'Updated successfully',
    updateError: 'Cannot update. Please try again.',
    personalInfo: 'Personal Information',
    contact: 'Contact',
    security: 'Security',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    passwordChanged: 'Password has been changed',
    passwordMismatch: 'New passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    contactEmail: 'Contact Email',
    updateEmail: 'Update Email',
    sendOtp: 'Send OTP Code',
    enterOtp: 'Enter OTP Code',
    verify: 'Verify',
    phoneNumber: 'Phone Number',
    dateOfBirth: 'Date of Birth',
    address: 'Address',
    notUpdated: 'Not updated',

    // Settings
    settings: 'Settings',
    language: 'Language',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    theme: 'Theme',
    lightMode: 'Light',
    darkMode: 'Dark',

    // Role
    admin: 'Administrator',
    staff: 'Staff',
    employee: 'Employee',
    user: 'User',
    tenant: 'Tenant',

    // Document
    uploadDocument: 'Upload Document',
    documentTitle: 'Document Title',
    selectFile: 'Select File',
    upload: 'Upload',
    uploadSuccess: 'Document uploaded successfully!',
    uploadError: 'Cannot upload document',
    internalDocuments: 'Company Internal Documents',
    noDocuments: 'No documents yet',
    addDocuments: 'Add documents to get started',
    processed: 'Processed',
    pending: 'Processing',
    uploadedAt: 'Uploaded at',
    fileSize: 'Size',
    new: 'NEW',

    // Error
    cannotLoadData: 'Cannot load data.',
    noPermission: 'You do not have permission to view this content.',
    somethingWentWrong: 'Something went wrong',
    tryAgain: 'Try again',
  },
};

export type TranslationKey = keyof typeof translations.vi;

export function t(key: TranslationKey, lang: Language = 'vi'): string {
  return translations[lang][key] || key;
}
